### PR TITLE
Changed organization name in license headers

### PR DESCRIPTION
**Pull request by DanieleDiBenedetto**

### CODE REVIEW

**Review by la10736 — APPROVED** [review]
LGTM

Just a red flag: why our CI didn't catch the wrong code format?

**Comment by DanieleDiBenedetto** [comment]
> LGTM
> 
> Just a red flag: why our CI didn't catch the wrong code format?

Maybe we are using different conf for the fmt in Visual Studio. Perhaps among the fmt parameters that are checked there isn't this specifical one (tabs size ?)

**Comment by la10736** [comment]
> > LGTM
> > Just a red flag: why our CI didn't catch the wrong code format?
> 
> Maybe we are using different conf for the fmt in Visual Studio. Perhaps among the fmt parameters that are checked there isn't this specifical one (tabs size ?)

Ok, but why CI didn't catch it?

**Comment by JackPiri** [comment]
> > > LGTM
> > > Just a red flag: why our CI didn't catch the wrong code format?
> > 
> > 
> > Maybe we are using different conf for the fmt in Visual Studio. Perhaps among the fmt parameters that are checked there isn't this specifical one (tabs size ?)
> 
> Ok, but why CI didn't catch it?

I am looking into this.

**Review by ptagl — APPROVED** [review]
It looks good to me, thanks!

About the discussion around formatting, I guess that `cargo fmt` accepts both formats without complaining, that's why the CI passed.

**Comment by DanieleDiBenedetto** [comment]
I'm gonna merge this one. If we find any relevant CI issue, we can fix it in a separate PR. Thanks everyone !

**Pull request merged**
